export const userDataObject = {
  uid: '',
  firstName: '',
  lastName: '',
  pronouns: '',
  approved: false,
  archived: false,
  role: '',
  bio: '',
  phoneNumber: '',
  iconNo: 0,
};

export const jobseekerUserInit = {
  navigator: '',
  lastCompletion: '',
  complete: false,
};

export const navigatorUserInit = {
  jobseekers: [],
};

export const jobseekerDataObject = {
  clientInfo: {
    Phone: '',
    'City/State': '',
    Ethnicity: '',
    Age: '',
    'Gender Identity': '',
    Sexuality: '',
    Veteran: '',
    Disability: '',
    'Housing Situation': '',
    'Currently Employed': '',
    'Prior Convictions': '',
  },
  skillsChecklist: {
    'Accounting Software': false,
    Administrative: false,
    Adobe: false,
    'Software Suite': false,
    Bilingual: false,
    'Brand Management': false,
    'Cold Calling': false,
    'Computer Software and Application': false,
    Software: false,
    CPR: false,
    'Customer Service': false,
    'Database Management': false,
    Excel: false,
    'Graphic Design': false,
    'Machinery Skills': false,
    'Marketing Campain Management': false,
    'Mobile Development': false,
    Multiligual: false,
    Negotiation: false,
    'Patient Scheduling Software': false,
    Philantropy: false,
    'Photo Editing': false,
    Photography: false,
    Photoshop: false,
  },
  industryInterest: {
    'App Type Jobs': false,
    'Accounting/Bookeeping': false,
    'Archetecture/Construction': false,
    'Audio/Video Technology & Communication': false,
    Barista: false,
    Bartender: false,
    Bookeeping: false,
    'Business Management and Administration': false,
    'Call Center': false,
    Caregiver: false,
    Carpenter: false,
    Cashier: false,
    'Data Entry': false,
    'Delivery Driver': false,
    'Education & Training': false,
    Engineering: false,
    Finance: false,
    Fundraising: false,
    'Graphic Design': false,
    'Health/Medical': false,
    Hospitality: false,
    'Human Resources': false,
  },
  milestones: {
    'job fair': 'incomplete',
    coenroll: 'incomplete',
    'training program': 'incomplete',
    assessment: 'incomplete',
    'hiring info': 'incomplete',
    internship: 'incomplete',
    workshop: 'incomplete',
    'job board': 'incomplete',
    'online profile': 'incomplete',
    resources: 'incomplete',
  },
};
